alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: demo-webhook
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
    - name: "null"          # tránh lỗi Helm chart
    - name: demo-webhook
      webhook_configs:
      - url: "https://eotmz9pc6v79i7q.m.pipedream.net"  # Webhook Pipedream thật của bạn
        send_resolved: true
