server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/week_5"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: local3306
    password: bongbibo9

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect  # Updated dialect

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-app
            client-secret: dzOFehaUJbw6vHrdtvim6PjEhWgvg49u
            scope: openid,profile,email,offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"  # Fixed redirect URI

        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/baeldung-sso

logging:
  level:
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG
    org.springframework.security: DEBUG