apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gs-spring-boot-k8s
  name: gs-spring-boot-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-spring-boot-k8s
  template:
    metadata:
      labels:
        app: gs-spring-boot-k8s
    spec:
      containers:
        - image: my-spring-app  # ← SỬA: dùng image bạn đã build
          imagePullPolicy: Never
          name: hello-spring-k8s
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5