apiVersion: v1
kind: Service
metadata:
  labels:
    app: gs-spring-boot-k8s
  name: gs-spring-boot-k8s
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gs-spring-boot-k8s
  type: ClusterIP