name: Build and Push Docker Image for k8s-hihi

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Lấy code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Cài JDK 21 (phù hợp Dockerfile)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build ứng dụng Spring Boot
      - name: Build Spring Boot application
        run: |
          cd week_7/k8s-hihi
          mvn clean package -DskipTests

      # 4️⃣ Đăng nhập Docker Hub (sửa về @v3)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hunghung711
          password: ${{ secrets.HUNGHUNG711 }}

      # 5️⃣ Build và push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./week_7/k8s-hihi
          push: true
          tags: |
            hunghung711/k8s-hihi:latest
            hunghung711/k8s-hihi:${{ github.sha }}
